### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Saad-Bashar** [didarulamin/recipe-react-native-app#1]
Great job, Few feedbacks - 

1. You do not need closing `TextInput` tag.
![Screenshot 2021-10-19 at 12 10 53 PM](https://user-images.githubusercontent.com/13269141/137842588-9584cc78-b458-4ec7-9b37-41bf786fc0b6.png)
2. Same with FlatList.
3. ` textAlign:justify` is not a good practice.

**Comment by didarulamin** [comment]
Thanks for your feedback.I will take care of this in future.
